#!/usr/bin/env python3

import cororun

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk as gtk, GLib as glib

async def get_input(label):
    w = gtk.Window()
    box = gtk.HBox()
    box.pack_start(gtk.Label(label), True, True, 0)
    entry = gtk.Entry()
    box.pack_start(entry, True, True, 0)
    w.add(box)
    w.show_all()
    async with cororun.suspending() as cont:
        entry.connect('activate', lambda _: cont(entry.get_text()))
        w.connect('delete-event', lambda _: cont(None))
    w.destroy()
    return cont.result

async def show_person_data():
    name = await get_input("Name:")
    if name is None:
        return
    address = await get_input("Address:")
    if address is None:
        return
    occupation = await get_input("Occupation:")
    if occupation is None:
        return
    l = gtk.Label()
    l.set_markup("<b>Name</b>\t\t{}\n<b>Address</b>\t\t{}\n<b>Occupation</b>\t{}"
                 .format(*map(glib.markup_escape_text,
                              (name, address, occupation))))
    w = gtk.Window()
    w.add(l)
    w.show_all()

def main():
    w = gtk.Window()
    btn = gtk.Button("Query person...")
    btn.connect('clicked', lambda _: cororun.start(show_person_data()))
    w.add(btn)
    w.connect('destroy', gtk.main_quit)
    w.show_all()
    gtk.main()

main()
